# Generated by Django 5.0.3 on 2025-11-17 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('main_role', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_role', models.CharField(blank=True, max_length=50, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, default=list, null=True)),
                ('keywords', models.JSONField(blank=True, default=list, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('participation', models.IntegerField(blank=True, null=True)),
                ('has_reward', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TeamRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leader_name', models.CharField(max_length=50)),
                ('main_role', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_role', models.CharField(blank=True, max_length=50, null=True)),
                ('skills', models.JSONField(blank=True, default=list, null=True)),
                ('looking_for', models.JSONField(blank=True, default=list, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('max_members', models.IntegerField(blank=True, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, default=list, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('has_reward', models.BooleanField(default=False)),
                ('participation', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='team_matching2.user')),
            ],
            options={
                'db_table': 'team_room',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('team', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, to='team_matching2.teamroom')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='team_matching2.user')),
            ],
            options={
                'db_table': 'team_member',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('team', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, to='team_matching2.teamroom')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='team_matching2.user')),
            ],
            options={
                'db_table': 'invitations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='pending', max_length=20, null=True)),
                ('team', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, to='team_matching2.teamroom')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='team_matching2.user')),
            ],
            options={
                'db_table': 'applications',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WaitingPool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('skills', models.JSONField(blank=True, default=list, null=True)),
                ('main_role', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_role', models.CharField(blank=True, max_length=100, null=True)),
                ('keywords', models.JSONField(blank=True, default=list, null=True)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='team_matching2.user')),
            ],
            options={
                'db_table': 'waiting_pool',
                'managed': True,
            },
        ),
    ]
